"""followers

Revision ID: 458d20b86ff8
Revises: b0d0baa55c47
Create Date: 2018-03-15 16:50:15.293490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458d20b86ff8'
down_revision = 'b0d0baa55c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
